@RpgCalendar.API_HostAddress = http://localhost:8000
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJlY2RhZDdmMS1hZjNhLTQ1YjAtYmQ3OS03MjMxZThjNGVhMTEiLCJleHAiOjE3MjQwMTI2NDd9.Kjkpv1PcfdqUlqe2tkT8d5zvZPZaoEu4TqEcrptuZGM

GET {{RpgCalendar.API_HostAddress}}/users/me/
Accept: application/json
Authorization: Bearer {{Token}}

###

POST {{RpgCalendar.API_HostAddress}}/users/login

###

POST {{RpgCalendar.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "displayName": "testuser"
}